//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtraccionTalentoHumanoWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Atraccion_Talento_HumanoEntities : DbContext
    {
        public Atraccion_Talento_HumanoEntities()
            : base("name=Atraccion_Talento_HumanoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreasProfesionales> AreasProfesionales { get; set; }
        public virtual DbSet<Cantones> Cantones { get; set; }
        public virtual DbSet<Certificados> Certificados { get; set; }
        public virtual DbSet<Curriculums> Curriculums { get; set; }
        public virtual DbSet<Distritos> Distritos { get; set; }
        public virtual DbSet<Escolaridades> Escolaridades { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Licencias> Licencias { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<Puestos_Usuario> Puestos_Usuario { get; set; }
        public virtual DbSet<Titulos> Titulos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
