//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtraccionTalentoHumanoWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idiomas
    {
        public int Id_Idioma { get; set; }
        public string Nombre { get; set; }
        public string NivelEscritura { get; set; }
        public string NivelLectura { get; set; }
        public string NivelConversacional { get; set; }
        public string Institucion { get; set; }
        public bool Certificado { get; set; }
        public int Cod_Usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
