//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtraccionTalentoHumanoWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencias
    {
        public int Id_Licencias { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Vencimiento { get; set; }
        public int Cod_Usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
